spring.application.name=lanchonete

spring.datasource.url=jdbc:postgresql://ep-shy-brook-an24rcpl.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_0OPjvb3koirU

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true